
name: Tests

on:
  push:
    branches: [ master ]
    paths-ignore:
      - 'README.md'  # Skip if only README changes
      - 'API.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - 'README.md'  # Ditto for PRs
      - 'API.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.2
      - name: Run Tests
        run: zig build test
